# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    env_file: .env
    build:
      context: .
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on: 
      db:
        condition: service_started

  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    expose:
      - 5432