# Generated by Django 4.2.3 on 2023-08-02 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emploee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('is_team_leed', models.BooleanField(default=False)),
                ('status_level', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='name')),
                ('like', models.TextField(verbose_name='Сильные стороны')),
                ('dislike', models.TextField(verbose_name='Области роста')),
                ('hard_skills', models.IntegerField(verbose_name='hard skill')),
                ('productivity', models.IntegerField(verbose_name='productivity')),
                ('communication', models.IntegerField(verbose_name='communication')),
                ('initiative', models.IntegerField(verbose_name='initiative2')),
                ('achievements', models.TextField(null=True)),
                ('ways_to_achieve', models.TextField(null=True)),
                ('team_leed_grade', models.IntegerField(null=True)),
                ('feedback_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('discription', models.TextField()),
                ('is_complited', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(related_name='projects', to='performance_review.emploee')),
            ],
        ),
        migrations.AddField(
            model_name='emploee',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='performance_review.team'),
        ),
        migrations.AddField(
            model_name='emploee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
