# Generated by Django 4.2.3 on 2023-11-24 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.TextField(verbose_name='Сильные стороны')),
                ('dislike', models.TextField(verbose_name='Области роста')),
                ('hard_skills', models.IntegerField()),
                ('productivity', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('initiative', models.IntegerField()),
                ('achievements', models.TextField(blank=True, null=True)),
                ('ways_to_achieve', models.TextField(blank=True, null=True)),
                ('leader_skills', models.IntegerField(blank=True, null=True)),
                ('feedback', models.IntegerField(blank=True, null=True)),
                ('teamwork', models.IntegerField(blank=True, null=True)),
                ('stress_resistance', models.IntegerField(blank=True, null=True)),
                ('feedback_date', models.DateField(blank=True, null=True)),
                ('about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_about', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
