# Generated by Django 4.2.2 on 2023-12-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "performance_review",
            "0002_employeefeedbackform_teamleadfeedbackform_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="teamleadfeedbackform",
            name="manager_approve",
            field=models.BooleanField(default=False),
        ),
    ]
