# Generated by Django 4.2.2 on 2024-01-11 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("performance_review", "0003_teamleadfeedbackform_manager_approve"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("stage", models.IntegerField(default=1)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_review",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
