# Generated by Django 4.2.2 on 2024-01-11 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("performance_review", "0004_performancereview"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeefeedbackform",
            name="performance_review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_form",
                to="performance_review.performancereview",
            ),
        ),
        migrations.AddField(
            model_name="teamleadfeedbackform",
            name="performance_review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teamlead_form",
                to="performance_review.performancereview",
            ),
        ),
    ]
