# Generated by Django 4.2.3 on 2024-01-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_providertoken_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providertoken',
            name='access_token',
            field=models.CharField(max_length=16000),
        ),
        migrations.AlterField(
            model_name='providertoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=16000, null=True),
        ),
    ]
